/**
 * Cloudflare Pages middleware — geo-block + regional locale auto-redirect.
 *
 * Runs at the edge BEFORE Astro static assets are served. Two responsibilities:
 *
 *   1. Geo-block. If CF-IPCountry is in the blocked list, serve the static
 *      "region not available" page with status 451 (RFC 7725).
 *
 *   2. Regional locale redirect. The language switcher only exposes the 5 base
 *      locales (en, de, es, pt, ru). When a user from a country with a regional
 *      variant (e.g. GB → en-gb, MX → es-mx) lands on the base locale path,
 *      we 302 them to the regional variant. Only a small allowlist of paths is
 *      regionalised (homepage + static pages + review listing) — individual
 *      review URLs are left alone, since regional reviews may not exist.
 *
 * When migrating to offshore hosting (post-MVP), replace this with the host's
 * equivalent: Nginx `geoip2` module, Apache `mod_geoip`, or a Node middleware.
 * The Astro build itself is host-agnostic.
 *
 * Sources of truth (edit the YAML, never this file):
 *   - data/blocked-countries.yaml   → functions/_blocked-countries.json
 *   - data/locales.yaml             → functions/_locale-routing.json
 * Both JSONs are regenerated by npm `prebuild` (scripts/build-*.mjs).
 */

import blockedData from './_blocked-countries.json' assert { type: 'json' };
import routingData from './_locale-routing.json'   assert { type: 'json' };

const BLOCKED_COUNTRIES: readonly string[] = blockedData.codes;
const REGIONAL_BY_COUNTRY: Record<string, string> = routingData.regionalByCountry;

const REGION_NOT_AVAILABLE_PATH = '/en/region-not-available/';

const STATIC_PASS_THROUGH = [
  '/_astro/',
  '/fonts/',
  '/brand/',
  '/casinos/',
  '/authors/',
  '/og-default.png',
  '/favicon.svg',
  '/favicon.ico',
  '/apple-touch-icon.png',
  '/robots.txt',
  '/sitemap.xml',
  '/sitemap.xsl',
];

const STATIC_EXT = /\.(svg|png|jpg|jpeg|webp|avif|ico|css|js|mjs|woff2?|ttf|otf|xml|xsl|txt|map)$/i;

/**
 * Path suffixes we are willing to regionalise. The user lands on /en/{suffix}/
 * and we redirect to /en-gb/{suffix}/. Path segments are identical across
 * a base + its regional variants (English variants all use 'reviews', Spanish
 * variants all use 'resenas', etc.) so a literal substitution works.
 *
 * Individual review pages (e.g. /en/reviews/slotoro/) are NOT in this list:
 * regional reviews may not exist yet, and we'd rather show the base-locale
 * review than redirect into a 404.
 */
const REGIONALIZABLE_SUFFIXES = new Set<string>([
  '',
  'about/',
  'contact/',
  'methodology/',
  'privacy-policy/',
  'terms-of-service/',
  'responsible-gambling/',
  'reviews/',     // English-family review listing
  'resenas/',     // Spanish-family review listing
  'avaliacoes/',  // Portuguese-family review listing
  'authors/',     // author index (when we add it)
]);

interface Env {
  ASSETS: { fetch: (req: Request | string) => Promise<Response> };
}

interface Context {
  request: Request;
  env: Env;
  next: () => Promise<Response>;
}

function isStaticAsset(path: string): boolean {
  if (STATIC_PASS_THROUGH.some((p) => path.startsWith(p))) return true;
  if (STATIC_EXT.test(path)) return true;
  return false;
}

/**
 * Compute the regional redirect target if applicable. Returns null when the
 * incoming request shouldn't be regionalised.
 */
function regionalRedirectTarget(path: string, country: string): string | null {
  const regional = REGIONAL_BY_COUNTRY[country];
  if (!regional) return null;                 // no regional variant for this country
  const baseLocale = regional.split('-')[0];  // 'en-gb' → 'en'

  // Match `/en/<suffix>` (with optional trailing slash) — we require a base
  // locale prefix.
  const m = path.match(new RegExp(`^/${baseLocale}(?:/(.*))?$`));
  if (!m) return null;

  const suffix = (m[1] ?? '');
  if (!REGIONALIZABLE_SUFFIXES.has(suffix)) return null;

  return `/${regional}/${suffix}`;
}

export const onRequest = async (context: Context): Promise<Response> => {
  const { request, env, next } = context;
  const url = new URL(request.url);
  const path = url.pathname;

  // Always allow the "blocked" page itself (avoid redirect loops)
  if (path.startsWith(REGION_NOT_AVAILABLE_PATH)) return next();

  // Static asset pass-through
  if (isStaticAsset(path)) return next();

  const country = (request.headers.get('cf-ipcountry') ?? '').toUpperCase();

  // 1) Geo-block — highest priority
  if (country && BLOCKED_COUNTRIES.includes(country)) {
    const blockedUrl = new URL(REGION_NOT_AVAILABLE_PATH, url);
    blockedUrl.searchParams.set('cc', country);
    const assetResp = await env.ASSETS.fetch(blockedUrl.toString());
    return new Response(assetResp.body, {
      status: 451, // Unavailable For Legal Reasons (RFC 7725)
      headers: {
        ...Object.fromEntries(assetResp.headers),
        'X-Geo-Block': 'true',
        'X-Geo-Block-Country': country,
        'Cache-Control': 'no-store',
      },
    });
  }

  // 2) Regional auto-redirect
  if (country) {
    const target = regionalRedirectTarget(path, country);
    if (target && target !== path) {
      const redirectUrl = new URL(target, url);
      // Preserve any incoming query string
      redirectUrl.search = url.search;
      return Response.redirect(redirectUrl.toString(), 302);
    }
  }

  return next();
};
